apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops-project
  name: backend
  labels:
    app: backend
spec:
  selector:
    matchLabels:
      app: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - image: rimbergaoui/backend
          name: backend
          ports:
            - containerPort: 8081
              name: http
          envFrom:
          - configMapRef: 
              name: appconfigmap
              

