apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: devops-project
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: rimbergaoui/frontend
          ports:
            - containerPort: 80
              name: http
          envFrom:
          - configMapRef: 
              name: appconfigmap

