apiVersion: v1
kind: Service
metadata:
  name: grafana
spec:
  selector:
    app: grafana
  ports:
    - port: 80
      targetPort: 3000
  type: LoadBalancer  # Changez ceci selon votre besoin : ClusterIP, LoadBalancer, NodePort, etc.
