server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://postgres-devops:5432/devops
    username : postgres
    password : rima
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database: postgresql
    database-platform:  org.hibernate.dialect.PostgreSQLDialect

mmanagement:
  endpoints:
    web:
      exposure:
        include: prometheus, health
  endpoint:
    metrics:
      enabled: true
